

class TrainingPipelineConfig:...

class DataIngestionConfig:...
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...